## PyTorch 是什么？
* 它是一个机遇Python的科学计算包，目标用户有两类
* 为了使用GPU来代替numpy
* 一个深度学习研究平台；提供最大的灵活性和速度

In [2]:
"""
张量（Tensors）
    张量类似于numpy和ndarrays,不同之处在于张量可以使用GPU
    来加快计算
"""

from __future__ import print_function
import torch

In [3]:
# 构建一个初始化5*3 的矩阵
x = torch.Tensor(5,3)
x

tensor([[8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39],
        [1.0653e-38, 1.0469e-38, 4.2246e-39],
        [1.0378e-38, 9.6429e-39, 9.2755e-39],
        [9.7346e-39, 1.0745e-38, 1.0102e-38]])

In [4]:
# 构建一个零矩阵，使用long的类型
x = torch.zeros(5,3,dtype = torch.long)
x


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [5]:
# 从数据中心直接构建一个张量（tensor）
x = torch.tensor([5.3,3])
x

tensor([5.3000, 3.0000])

In [9]:
# 或者在已有张量（tensor）中构建一个张量（tensor）.
# 这些方法将重用输入张量（tensor）的属性

x = x.new_ones(5,3,dtype=torch.double)
print(x)

x = torch.randn_like(x,dtype=torch.float)# 覆盖类型
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.7503,  0.4383, -0.7689],
        [-1.2677,  1.0847,  0.7349],
        [ 0.6252, -0.7560, -0.3890],
        [ 0.4024, -0.5974,  0.9545],
        [ 2.1731, -0.2477, -0.5647]])


In [10]:
# 获取张量（tensor）大小
print(x.size())


torch.Size([5, 3])


In [13]:
x.size()  # 实际上是一个元组，所以他支持元组的所有操作

torch.Size([5, 3])

In [14]:
y = torch.rand(5,3)
print("x=")
print(x)

print("y=")
print(y)

print(x+y)

x=
tensor([[ 0.7503,  0.4383, -0.7689],
        [-1.2677,  1.0847,  0.7349],
        [ 0.6252, -0.7560, -0.3890],
        [ 0.4024, -0.5974,  0.9545],
        [ 2.1731, -0.2477, -0.5647]])
y=
tensor([[0.1516, 0.9980, 0.0078],
        [0.5385, 0.4169, 0.3607],
        [0.7030, 0.7847, 0.9362],
        [0.3322, 0.6552, 0.8517],
        [0.1922, 0.6477, 0.3556]])
tensor([[ 0.9020,  1.4363, -0.7611],
        [-0.7292,  1.5016,  1.0955],
        [ 1.3282,  0.0287,  0.5472],
        [ 0.7346,  0.0578,  1.8061],
        [ 2.3653,  0.4001, -0.2092]])


In [15]:
print(torch.add(x,y))

tensor([[ 0.9020,  1.4363, -0.7611],
        [-0.7292,  1.5016,  1.0955],
        [ 1.3282,  0.0287,  0.5472],
        [ 0.7346,  0.0578,  1.8061],
        [ 2.3653,  0.4001, -0.2092]])


In [16]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 0.9020,  1.4363, -0.7611],
        [-0.7292,  1.5016,  1.0955],
        [ 1.3282,  0.0287,  0.5472],
        [ 0.7346,  0.0578,  1.8061],
        [ 2.3653,  0.4001, -0.2092]])


In [17]:
# 把x加到y上
y.add_(x)
print(y)

tensor([[ 0.9020,  1.4363, -0.7611],
        [-0.7292,  1.5016,  1.0955],
        [ 1.3282,  0.0287,  0.5472],
        [ 0.7346,  0.0578,  1.8061],
        [ 2.3653,  0.4001, -0.2092]])


### 可以使用所有的numpy索引操作


In [19]:
print(x)
print(x[:1])

tensor([[ 0.7503,  0.4383, -0.7689],
        [-1.2677,  1.0847,  0.7349],
        [ 0.6252, -0.7560, -0.3890],
        [ 0.4024, -0.5974,  0.9545],
        [ 2.1731, -0.2477, -0.5647]])
tensor([[ 0.7503,  0.4383, -0.7689]])


In [20]:
print(x[:,1])

tensor([ 0.4383,  1.0847, -0.7560, -0.5974, -0.2477])


In [21]:
# 调整大小：如果要调整张量/重塑张量，可以使用torch.view

x = torch.randn(4,4)
x

tensor([[ 0.1481,  1.2866, -0.7092, -0.6955],
        [ 0.3258,  0.5852, -1.2924, -1.1617],
        [ 1.1531, -0.2233, -2.0505,  0.3810],
        [ 0.8424,  1.6083,  0.2965, -0.3321]])

In [22]:
y = x.view(16)
y

tensor([ 0.1481,  1.2866, -0.7092, -0.6955,  0.3258,  0.5852, -1.2924, -1.1617,
         1.1531, -0.2233, -2.0505,  0.3810,  0.8424,  1.6083,  0.2965, -0.3321])

In [23]:
# -1的意思是没有指定维度
z= x.view(-1,8)
z

tensor([[ 0.1481,  1.2866, -0.7092, -0.6955,  0.3258,  0.5852, -1.2924, -1.1617],
        [ 1.1531, -0.2233, -2.0505,  0.3810,  0.8424,  1.6083,  0.2965, -0.3321]])

In [24]:
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [25]:
# 如果有一个单元张量，使用。item()的值作为Python数字
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0379])
0.0379331111907959


###### 稍后阅读
* https://pytorch.org/doc/stable/torch.html
* 转置，索引，数学运算，线性代数，随机数

In [ ]:
## p5